site_name: sqlcli
site_description: "A command line interface (CLI) for interacting with SQLModel."
repo_url: https://github.com/samedwardes/sqlcli
repo_name: 'samedwardes/sqlcli'
edit_uri: ''

theme:
  name: material
  icon:
    logo: fontawesome/solid/terminal
  favicon: img/terminal-solid.svg
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate

markdown_extensions:
  - mdx_include
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

# markdown_extensions:
# - toc:
#     permalink: true
# - markdown.extensions.codehilite:
#     guess_lang: false
# - admonition
# - codehilite
# - extra
# - pymdownx.superfences:
#     custom_fences:
#     - name: mermaid
#       class: mermaid
#       format: !!python/name:pymdownx.superfences.fence_code_format ''
# - pymdownx.tabbed:
#     alternate_style: true
# - mdx_include

plugins:
  - search
  - include-markdown

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/samedwardes/sqlcli
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/therealsamlam
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samedwardes

nav:
  - Home: 'index.md'
  - changelog.md
  - contributing.md
  - api/api-reference.md
  - Tutorial - User Guide:
    - tutorial/getting-started.md
    - tutorial/using-demo-db.md

